version: "3.9"

services:
#  db:
#    image: postgres:13.4-alpine

  web:
    build: app

    command: uvicorn main:app --reload --host 0.0.0.0 --port 8040
    ports:
      - 8040:8040
    volumes:
      - type: bind
        source: ./app
        target: /app

