version: "3.5"

networks:
  local_db:
    driver: bridge
    name: global_access
    ipam:
      driver: default
  web_app:
    driver: bridge
    name: access_to_db
    ipam:
      driver: default


services:
  db:
    image: postgres:13
#    image: postgres:13
    command: postgres -c max_connections=300 -c shared_buffers=80MB
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PG_SUPERUSER_NAME}
      POSTGRES_PASSWORD: ${PG_SUPERUSER_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postrges-db-data-t1:/var/lib/postgresql/data
    networks:
      - local_db
    ports:
      - '${PGPORT}:5432'
    expose:
      - '${PGPORT}'

  web:
    image: daniinxorchenabo/gh_server

#    container_name: daniinxorchenabo/gh_server:heroku

    networks:
      - local_db
      - web_app
    env_file:
      - .env
    environment:
      PGHOST: pgsql-server
    depends_on:
      - db
#    command: /bin/sh

    command: >
      bash -c "cd ../..
      && cd code/gh_server/app/src/piccolo_db
      && sleep 1
      && piccolo --diagnose
      && piccolo migrations forwards gh
      && cd ../..
      && uvicorn main:app --reload --host 0.0.0.0 --port ${APP_PORT}"

    links:
      - "db"
      - "db:pgsql-server"

    ports:
      - '${APP_PORT}:${APP_PORT}'

    volumes:
      - type: bind
        source: .
        target: /code/gh_server

  pgadmin:
    image: dpage/pgadmin4:5.7
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    networks:
      - local_db
      - web_app
    ports:
      - '${PGADMIN_PORT}:80'
    volumes:
      - pgadmin-data-t1:/var/lib/pgadmin
    links:
      - "db:pgsql-server"

volumes:
  postrges-db-data-t1:
  pgadmin-data-t1:




