"""create user table

Revision ID: 7281952c531e
Revises: 
Create Date: 2021-10-08 21:48:15.015984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7281952c531e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_')
    # ### end Alembic commands ###
