"""create user table

Revision ID: 9f5ec2decc2f
Revises: 92f95fabe941
Create Date: 2021-10-13 22:49:19.676471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f5ec2decc2f'
down_revision = '92f95fabe941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_', sa.Column('username', sa.String(length=100), nullable=False))
    op.add_column('user_', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('user_', sa.Column('surname', sa.String(length=50), nullable=False))
    op.add_column('user_', sa.Column('hashed_password', sa.String(length=4096), nullable=False))
    op.add_column('user_', sa.Column('email', sa.String(length=100), nullable=False))
    op.add_column('user_', sa.Column('_scopes', postgresql.ARRAY(sa.String(length=1)), nullable=False))
    op.create_unique_constraint(None, 'user_', ['email'])
    op.create_unique_constraint(None, 'user_', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, table_name='user_', type_='unique')
    # op.drop_constraint(None, table_name='user_', type_='unique')
    op.drop_column('user_', '_scopes')
    op.drop_column('user_', 'email')
    op.drop_column('user_', 'hashed_password')
    op.drop_column('user_', 'surname')
    op.drop_column('user_', 'name')
    op.drop_column('user_', 'username')
    # ### end Alembic commands ###
